### ISSUE TITLE
Mac上PdfLatex编译报错

### ISSUE THREAD

**Issue by kubertalk** [zeakey/shu-thesis#3]
### Mac上采用PdfLatex编译报错，
错误代码为：
Font cyberb61 at 723 not found.

其他信息大致是说Mac上Texlive里的字体少了什么。
Win环境下编译没问题。

不知道是哪里有问题？

**Comment by zeakey** [comment]
这里有个类似的字体缺失问题<https://tex.stackexchange.com/questions/284881/chinese-ctex-tex-live-2015-on-ubuntu>。
在Linux、OSX系统上用`xelatex`代替`pdflatex`进行编译。
在<https://github.com/zeakey/shu-thesis/commit/3dc769ed26ee6071efdbaaae58e1ae076148c4b6>里我加了个简单的OS判断。
